### ISSUE TITLE
Fix auto-join action

### ISSUE THREAD

**Issue by BaseMax** [POSSF/Join#3]

**Comment by BaseMax** [comment]
```
/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/orgs/POSSF/members/razaghimahdi: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)
    from /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
    from /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
    from /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
```


Fixed by adding variable secrets.

**Comment by BaseMax** [comment]
```/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': PUT https://api.github.com/teams/4892021/memberships/razaghimahdi: 403 - You must be an organization owner or team maintainer to add a team membership. // See: https://docs.github.com/rest/reference/teams#add-or-update-team-membership-for-a-user (Octokit::Forbidden)
    from /usr/local/bundle/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
```

I not sure. I have to add myself to that team?

**Comment by BaseMax** [comment]
403 - You must be an organization owner or team maintainer to add a team membership

![Screenshot_2021-06-17_20-33-08](https://user-images.githubusercontent.com/2658040/122433207-40e46800-cfab-11eb-8055-8f815539585c.png)

**Comment by BaseMax** [comment]
https://github.com/POSSF/Join/runs/2850816683?check_suite_focus=true

Done and sovled.
```
Post job cleanup.
/usr/bin/git version
git version 2.32.0
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
```

**Comment by BaseMax** [comment]
Thanks to Brian

**Comment by BaseMax** [comment]
**/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': PUT https://api.github.com/teams/4892021/memberships/razaghimahdi: 403 - You must be an organization owner or team maintainer to add a team membership. // See: https://docs.github.com/rest/reference/teams#add-or-update-team-membership-for-a-user (Octokit::Forbidden)**

**Comment by BaseMax** [comment]
```await octokit.request('PUT /orgs/{org}/teams/{team_slug}/memberships/{username}', {
  org: 'org',
  team_slug: 'team_slug',
  username: 'username',
  role: 'role'
})```
